### ISSUE TITLE
quickcheck tests

### ISSUE THREAD

**Issue by yoshuawuyts** [datrs/merkle-tree-stream#6]
We should do some property testing after merging #5

**Comment by khernyo** [comment]
I'm gonna work on this if it's not taken yet.

At a glance, I'm not sure I can think of a lot of properties to test for, so let me know if you had anything specific in mind.

**Comment by yoshuawuyts** [comment]
@khernyo that would be great!

I'm thinking starting off with `.next()` might be good. It'll be using some fun `flat-tree` semantics which may also be good to check (e.g. create the parent hashes, populate the root hashes, etc)

How does that sound?

**Comment by khernyo** [comment]
I'm gonna dive in, and we will see :)
